
function band_doa_no_la_config(this_block)

  % Revision History:
  %
  %   28-Apr-2022  (15:32 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/Workspace/simulink_models/DoA/ROACH2/doa_arte/band/rtl/band_doa_no_la.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('band_doa_no_la');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;
  myname = this_block.blockName; %This is the name of the black box block
  bb_mask = get_param(myname,'Parent'); %This is the name of the black box subsystem
  din_width = str2num(get_param(bb_mask, 'din_width'));
  din_point = str2num(get_param(bb_mask, 'din_point'));
  parallel = str2num(get_param(bb_mask, 'parallel'));
  vector_len = str2num(get_param(bb_mask, 'vector_len'));
  bands = str2num(get_param(bb_mask, 'bands'));
  pre_acc_delay = str2num(get_param(bb_mask, 'pre_acc_delay'));
  pre_acc_shift = str2num(get_param(bb_mask, 'pre_acc_shift'));
  acc_width = str2num(get_param(bb_mask, 'acc_width'));
  acc_point = str2num(get_param(bb_mask, 'acc_point'));
  dout_width = str2num(get_param(bb_mask, 'dout_width'));
  

  this_block.addSimulinkInport('din1_re');
  this_block.addSimulinkInport('din1_im');
  this_block.addSimulinkInport('din2_re');
  this_block.addSimulinkInport('din2_im');
  this_block.addSimulinkInport('din_valid');
  this_block.addSimulinkInport('new_acc');

  this_block.addSimulinkOutport('r11');
  this_block.addSimulinkOutport('r22');
  this_block.addSimulinkOutport('r12');
  this_block.addSimulinkOutport('dout_valid');
  this_block.addSimulinkOutport('band_number');

  dout_valid_port = this_block.port('dout_valid');
  dout_valid_port.setType('UFix_1_0');
  dout_valid_port.useHDLVector(false);
  
  r11_port = this_block.port('r11');
  r11_port.setType(strcat('UFix_', int2str(dout_width), '_0'));

  r12_port = this_block.port('r12');
  r12_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  
  r22_port = this_block.port('r22');
  r22_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  
  band_port = this_block.port('band_number');
  band_port.setType(strcat('UFix_', int2str(ceil(log2(bands))),'_0'));
  
  
  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    % (!) Port 'din1_re' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'din1_im' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'din2_re' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'din2_im' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

    if (this_block.port('new_acc').width ~= 1);
      this_block.setError('Input data type for port "new_acc" must have width=1.');
    end

    this_block.port('new_acc').useHDLVector(false);

  % (!) Port 'r11' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'r22' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'r12' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'band_number' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('DIN_WIDTH','integer',int2str(din_width));
  this_block.addGeneric('DIN_POINT','integer',int2str(din_point));
  this_block.addGeneric('PARALLEL','integer',int2str(parallel));
  this_block.addGeneric('VECTOR_LEN','integer',int2str(vector_len));
  this_block.addGeneric('BANDS','integer',int2str(bands));
  this_block.addGeneric('PRE_ACC_DELAY','integer',int2str(pre_acc_delay));
  this_block.addGeneric('PRE_ACC_SHIFT','integer',int2str(pre_acc_shift));
  this_block.addGeneric('ACC_WIDTH','integer',int2str(acc_width));
  this_block.addGeneric('ACC_POINT','integer',int2str(acc_point));
  this_block.addGeneric('DOUT_WIDTH','integer',int2str(dout_width));
  this_block.addGeneric('CLOG_BAND','integer',int2str(ceil(log2(bands))));

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('rtl/band_doa_no_la.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

