
function quad_eigen_iterative_config(this_block)

  % Revision History:
  %
  %   28-Apr-2022  (18:13 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/Workspace/simulink_models/DoA/ROACH2/doa_arte/band/rtl/quad_eigen_iterative.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('quad_eigen_iterative');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;
  
  myname = this_block.blockName; %This is the name of the black box block
  bb_mask = get_param(myname,'Parent'); %This is the name of the black box subsystem
  din_width = str2num(get_param(bb_mask, 'din_width'));
  din_point = str2num(get_param(bb_mask, 'din_point'));
  sqrt_width = str2num(get_param(bb_mask, 'sqrt_width'));
  sqrt_point = str2num(get_param(bb_mask, 'sqrt_point'));
  dout_width = str2num(get_param(bb_mask, 'dout_width'));
  dout_point = str2num(get_param(bb_mask, 'dout_point'));
  bands = str2num(get_param(bb_mask, 'bands'));
  fifo_depth = str2num(get_param(bb_mask, 'fifo_depth'));

  this_block.addSimulinkInport('r11');
  this_block.addSimulinkInport('r22');
  this_block.addSimulinkInport('r12');
  this_block.addSimulinkInport('din_valid');
  this_block.addSimulinkInport('band_in');

  this_block.addSimulinkOutport('lamb1');
  this_block.addSimulinkOutport('lamb2');
  this_block.addSimulinkOutport('eigen1_y');
  this_block.addSimulinkOutport('eigen2_y');
  this_block.addSimulinkOutport('eigen_x');
  this_block.addSimulinkOutport('dout_valid');
  this_block.addSimulinkOutport('dout_error');
  this_block.addSimulinkOutport('band_out');
  this_block.addSimulinkOutport('fifo_full');

  dout_valid_port = this_block.port('dout_valid');
  dout_valid_port.setType('UFix_1_0');
  dout_valid_port.useHDLVector(false);
  dout_error_port = this_block.port('dout_error');
  dout_error_port.setType('UFix_1_0');
  dout_error_port.useHDLVector(false);
  fifo_full_port = this_block.port('fifo_full');
  fifo_full_port.setType('UFix_1_0');
  fifo_full_port.useHDLVector(false);

  l1_port = this_block.port('lamb1');
  l1_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  l2_port = this_block.port('lamb2');
  l2_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  
  eig1_port = this_block.port('eigen1_y');
  eig1_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  eig2_port = this_block.port('eigen2_y');
  eig2_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  eigx_port = this_block.port('eigen_x');
  eigx_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  
  bandout_port = this_block.port('band_out');
  bandout_port.setType(strcat('UFix_', int2str(ceil(log2(bands))),'_0'));
  
  
  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    % (!) Port 'r11' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'r22' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'r12' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

    % (!) Port 'band_in' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

  % (!) Port 'lamb1' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'lamb2' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'eigen1_y' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'eigen2_y' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'eigen_x' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'band_out' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('DIN_WIDTH','integer',int2str(din_width));
  this_block.addGeneric('DIN_POINT','integer',int2str(din_point));
  this_block.addGeneric('SQRT_WIDTH','integer',int2str(sqrt_width));
  this_block.addGeneric('SQRT_POINT','integer',int2str(sqrt_point));
  this_block.addGeneric('DOUT_WIDTH','integer',int2str(dout_width));
  this_block.addGeneric('DOUT_POINT','integer',int2str(dout_point));
  this_block.addGeneric('BANDS','integer',int2str(bands));
  this_block.addGeneric('FIFO_DEPTH','integer',int2str(fifo_depth));
  this_block.addGeneric('CLOG_BANDS','integer',int2str(ceil(log2(bands))));

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('rtl/quad_eigen_iterative.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

