`include "/home/Workspace/seba/cordic_test/rtl/piso.v"
`include "/home/Workspace/seba/cordic_test/rtl/arctan2.v"
`include "/home/Workspace/seba/cordic_test/rtl/arctan.v"
`include "/home/Workspace/seba/cordic_test/rtl/autoscale.v"
`include "/home/Workspace/seba/cordic_test/rtl/bram_infer.v"
`include "/home/Workspace/seba/cordic_test/rtl/first_one_finder.v"
`include "/home/Workspace/seba/cordic_test/rtl/rom.v"
`include "/home/Workspace/seba/cordic_test/rtl/skid_buffer.v"
