
function rfi_detection_config(this_block)

  % Revision History:
  %
  %   09-May-2022  (11:58 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/roach/Workspace/simulink_models/RFI_detection/ROACH2/model/rtl/rfi_detection.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('rfi_detection');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;
  myname = this_block.blockName;
  bb_mask = get_param(myname,'Parent'); %This is the name of the black box subsystem
  din_width = str2num(get_param(bb_mask, 'din_width'));
  channel_addr = str2num(get_param(bb_mask, 'channel_addr'));
  cast_shift = str2num(get_param(bb_mask, 'cast_shift'));
  cast_delay = str2num(get_param(bb_mask, 'cast_delay'));
  cast_width = str2num(get_param(bb_mask, 'cast_width'));
  cast_point = str2num(get_param(bb_mask, 'cast_point'));
  post_mult_delay = str2num(get_param(bb_mask, 'post_mult_delay'));
  acc_width = str2num(get_param(bb_mask, 'acc_width'));
  post_acc_shift = str2num(get_param(bb_mask, 'post_acc_shift'));
  post_acc_width = str2num(get_param(bb_mask, 'post_acc_width'));
  post_acc_point = str2num(get_param(bb_mask, 'post_acc_point'));
  post_acc_delay = str2num(get_param(bb_mask, 'post_acc_delay'));
  dout_shift = str2num(get_param(bb_mask, 'dout_shift'));
  dout_width = str2num(get_param(bb_mask, 'dout_width'));
  dout_point = str2num(get_param(bb_mask, 'dout_point'));
  debug = str2num(get_param(bb_mask, 'debug'));
  
  
  this_block.addSimulinkInport('sig_re');
  this_block.addSimulinkInport('sig_im');
  this_block.addSimulinkInport('ref_re');
  this_block.addSimulinkInport('ref_im');
  this_block.addSimulinkInport('din_valid');
  this_block.addSimulinkInport('sync_in');
  this_block.addSimulinkInport('acc_len');
  this_block.addSimulinkInport('cnt_rst');

  this_block.addSimulinkOutport('pow_data');
  this_block.addSimulinkOutport('corr_data');
  this_block.addSimulinkOutport('dout_valid');
  this_block.addSimulinkOutport('warning');

  dout_valid_port = this_block.port('dout_valid');
  dout_valid_port.setType('UFix_1_0');
  dout_valid_port.useHDLVector(false);
  
  pow_data_port = this_block.port('pow_data');
  pow_data_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  corr_data_port = this_block.port('corr_data');
  corr_data_port.setType(strcat('UFix_', int2str(dout_width), '_0'));
  
  warning_port = this_block.port('warning');
  warning_port.setType('UFix_1_0');
  warning_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    % (!) Port 'sig_re' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'sig_im' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'ref_re' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    % (!) Port 'ref_im' appeared to have dynamic type in the HDL -- please add type checking as appropriate;

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

    if (this_block.port('sync_in').width ~= 1);
      this_block.setError('Input data type for port "sync_in" must have width=1.');
    end

    this_block.port('sync_in').useHDLVector(false);

    if (this_block.port('acc_len').width ~= 32);
      this_block.setError('Input data type for port "acc_len" must have width=32.');
    end

    if (this_block.port('cnt_rst').width ~= 1);
      this_block.setError('Input data type for port "cnt_rst" must have width=1.');
    end

    this_block.port('cnt_rst').useHDLVector(false);

  % (!) Port 'pow_data' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  % (!) Port 'corr_data' appeared to have dynamic type in the HDL
  % --- you must add an appropriate type setting for this port
  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('DIN_WIDTH','integer',int2str(din_width));
  this_block.addGeneric('CHANNEL_ADDR','integer',int2str(channel_addr));
  this_block.addGeneric('CAST_SHIFT','integer',int2str(cast_shift));
  this_block.addGeneric('CAST_DELAY','integer',int2str(cast_delay));
  this_block.addGeneric('CAST_WIDHT','integer',int2str(cast_width));
  this_block.addGeneric('CAST_POINT','integer',int2str(cast_point));
  this_block.addGeneric('POST_MULT_DELAY','integer',int2str(post_mult_delay));
  this_block.addGeneric('ACC_WIDTH','integer',int2str(acc_width));
  this_block.addGeneric('POST_ACC_SHIFT','integer',int2str(post_acc_shift));
  this_block.addGeneric('POST_ACC_WIDTH','integer',int2str(post_acc_width));
  this_block.addGeneric('POST_ACC_POINT','integer',int2str(post_acc_point));
  this_block.addGeneric('POST_ACC_DELAY','integer',int2str(post_acc_delay));
  this_block.addGeneric('DOUT_SHIFT','integer',int2str(dout_shift));
  this_block.addGeneric('DOUT_WIDTH','integer',int2str(dout_width));
  this_block.addGeneric('DOUT_POINT','integer',int2str(dout_point));
  this_block.addGeneric('DEBUG','integer',int2str(debug));

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('includes.v');
  this_block.addFile('rtl/rfi_detection.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

