
function eigen_top_config(this_block)

  % Revision History:
  %
  %   13-May-2021  (18:21 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/franco/seba/doa_test/vec_linalg2/eigen_top.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('eigen_top');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('r11');
  this_block.addSimulinkInport('r22');
  this_block.addSimulinkInport('r12');
  this_block.addSimulinkInport('din_valid');

  this_block.addSimulinkOutport('lamb1');
  this_block.addSimulinkOutport('lamb2');
  this_block.addSimulinkOutport('eigen1_y');
  this_block.addSimulinkOutport('eigen2_y');
  this_block.addSimulinkOutport('eigen_x');
  this_block.addSimulinkOutport('addr');
  this_block.addSimulinkOutport('dout_valid');

  lamb1_port = this_block.port('lamb1');
  lamb1_port.setType('UFix_16_0');
  lamb2_port = this_block.port('lamb2');
  lamb2_port.setType('UFix_16_0');
  eigen1_y_port = this_block.port('eigen1_y');
  eigen1_y_port.setType('UFix_16_0');
  eigen2_y_port = this_block.port('eigen2_y');
  eigen2_y_port.setType('UFix_16_0');
  eigen_x_port = this_block.port('eigen_x');
  eigen_x_port.setType('UFix_16_0');
  addr_port = this_block.port('addr');
  addr_port.setType('UFix_9_0');
  dout_valid_port = this_block.port('dout_valid');
  dout_valid_port.setType('UFix_1_0');
  dout_valid_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('r11').width ~= 16);
      this_block.setError('Input data type for port "r11" must have width=16.');
    end

    if (this_block.port('r22').width ~= 16);
      this_block.setError('Input data type for port "r22" must have width=16.');
    end

    if (this_block.port('r12').width ~= 16);
      this_block.setError('Input data type for port "r12" must have width=16.');
    end

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('DIN_WIDTH','integer','16');
  this_block.addGeneric('DIN_POINT','integer','15');
  this_block.addGeneric('SQRT_IN_WIDTH','integer','10');
  this_block.addGeneric('SQRT_IN_POINT','integer','7');
  this_block.addGeneric('DOUT_WIDTH','integer','16');
  this_block.addGeneric('DOUT_POINT','integer','13');
  this_block.addGeneric('SQRT_FILE','string','"/home/franco/seba/doa_test/vec_linalg2/init_mem/sqrt.hex"');
    % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
    path = '/home/franco/seba/doa_test/vec_linalg2/';

  this_block.addFile(strcat(path, 'eigen_top.v'));

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

