
function packetizer_top_config(this_block)

  % Revision History:
  %
  %   28-Feb-2022  (16:32 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/Workspace/simulink_models/Ten_Gbe/packet_test/packetizer_top.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('packetizer_top');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('din');
  this_block.addSimulinkInport('din_valid');
  this_block.addSimulinkInport('pkt_len');
  this_block.addSimulinkInport('sleep_cycles');
  this_block.addSimulinkInport('config_tx_dest_ip');
  this_block.addSimulinkInport('config_tx_dest_port');

  this_block.addSimulinkOutport('tx_data');
  this_block.addSimulinkOutport('tx_valid');
  this_block.addSimulinkOutport('tx_dest_ip');
  this_block.addSimulinkOutport('tx_dest_port');
  this_block.addSimulinkOutport('tx_eof');
  this_block.addSimulinkOutport('fifo_full');

  tx_data_port = this_block.port('tx_data');
  tx_data_port.setType('UFix_64_0');
  tx_valid_port = this_block.port('tx_valid');
  tx_valid_port.setType('UFix_1_0');
  tx_valid_port.useHDLVector(false);
  tx_dest_ip_port = this_block.port('tx_dest_ip');
  tx_dest_ip_port.setType('UFix_32_0');
  tx_dest_port_port = this_block.port('tx_dest_port');
  tx_dest_port_port.setType('UFix_16_0');
  tx_eof_port = this_block.port('tx_eof');
  tx_eof_port.setType('UFix_1_0');
  tx_eof_port.useHDLVector(false);
  fifo_full_port = this_block.port('fifo_full');
  fifo_full_port.setType('UFix_1_0');
  fifo_full_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('din').width ~= 128);
      this_block.setError('Input data type for port "din" must have width=128.');
    end

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

    if (this_block.port('pkt_len').width ~= 32);
      this_block.setError('Input data type for port "pkt_len" must have width=32.');
    end

    if (this_block.port('sleep_cycles').width ~= 32);
      this_block.setError('Input data type for port "sleep_cycles" must have width=32.');
    end

    if (this_block.port('config_tx_dest_ip').width ~= 32);
      this_block.setError('Input data type for port "config_tx_dest_ip" must have width=32.');
    end

    if (this_block.port('config_tx_dest_port').width ~= 32);
      this_block.setError('Input data type for port "config_tx_dest_port" must have width=32.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  %this_block.addFile('rtl/bram_infer.v');
  %this_block.addFile('rtl/skid_buffer.v');
  %this_block.addFile('rtl/piso.v');
  %this_block.addFile('rtl/tge_write_packetizer.v');
  this_block.addFile('includes.v');
  this_block.addFile('rtl/packetizer_top.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

