
function pfb_fft_8in_2048ch_config(this_block)

  % Revision History:
  %
  %   02-Aug-2021  (20:08 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/arte_black_box/hdl_codes/pfb_fft_8in_2048ch.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('pfb_fft_8in_2048ch');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;
   
  this_block.addSimulinkInport('sync_in');
  this_block.addSimulinkInport('dat0');
  this_block.addSimulinkInport('dat1');
  this_block.addSimulinkInport('dat2');
  this_block.addSimulinkInport('dat3');
  this_block.addSimulinkInport('dat4');
  this_block.addSimulinkInport('dat5');
  this_block.addSimulinkInport('dat6');
  this_block.addSimulinkInport('dat7');
  
  this_block.addSimulinkOutport('sync_out');
  this_block.addSimulinkOutport('ch0');
  this_block.addSimulinkOutport('ch1');
  this_block.addSimulinkOutport('ch2');
  this_block.addSimulinkOutport('ch3');
  this_block.addSimulinkOutport('fft_ovf');
  

  ch0_port = this_block.port('ch0');
  ch0_port.setType('UFix_36_0');
  ch1_port = this_block.port('ch1');
  ch1_port.setType('UFix_36_0');
  ch2_port = this_block.port('ch2');
  ch2_port.setType('UFix_36_0');
  ch3_port = this_block.port('ch3');
  ch3_port.setType('UFix_36_0');
  fft_ovf_port = this_block.port('fft_ovf');
  fft_ovf_port.setType('UFix_2_0');
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('dat0').width ~= 8);
      this_block.setError('Input data type for port "dat0" must have width=8.');
    end

    if (this_block.port('dat1').width ~= 8);
      this_block.setError('Input data type for port "dat1" must have width=8.');
    end

    if (this_block.port('dat2').width ~= 8);
      this_block.setError('Input data type for port "dat2" must have width=8.');
    end

    if (this_block.port('dat3').width ~= 8);
      this_block.setError('Input data type for port "dat3" must have width=8.');
    end

    if (this_block.port('dat4').width ~= 8);
      this_block.setError('Input data type for port "dat4" must have width=8.');
    end

    if (this_block.port('dat5').width ~= 8);
      this_block.setError('Input data type for port "dat5" must have width=8.');
    end

    if (this_block.port('dat6').width ~= 8);
      this_block.setError('Input data type for port "dat6" must have width=8.');
    end

    if (this_block.port('dat7').width ~= 8);
      this_block.setError('Input data type for port "dat7" must have width=8.');
    end

    if (this_block.port('sync_in').width ~= 1);
      this_block.setError('Input data type for port "sync_in" must have width=1.');
    end

    this_block.port('sync_in').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('includes.v');
  this_block.addFile('rtl/pfb_fft_8in_2048ch.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

