
function autoscale_top_config(this_block)

  % Revision History:
  %
  %   01-Jul-2021  (14:15 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/cordic_atan/autoscale_top.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('autoscale_top');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('din1');
  this_block.addSimulinkInport('din2');
  this_block.addSimulinkInport('din_valid');

  this_block.addSimulinkOutport('dout1');
  this_block.addSimulinkOutport('dout2');
  this_block.addSimulinkOutport('dout_valid');
  this_block.addSimulinkOutport('shift_val');

  dout1_port = this_block.port('dout1');
  dout1_port.setType('UFix_32_0');
  dout2_port = this_block.port('dout2');
  dout2_port.setType('UFix_32_0');
  dout_valid_port = this_block.port('dout_valid');
  dout_valid_port.setType('UFix_1_0');
  dout_valid_port.useHDLVector(false);
  shift_val_port = this_block.port('shift_val');
  shift_val_port.setType('UFix_6_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('din1').width ~= 32);
      this_block.setError('Input data type for port "din1" must have width=32.');
    end

    if (this_block.port('din2').width ~= 32);
      this_block.setError('Input data type for port "din2" must have width=32.');
    end

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('hdl_codes/autoscale_top.v');
  this_block.addFile('hdl_codes/autoscale.v');
  this_block.addFile('hdl_codes/first_one_finder.v');
  this_block.addFile('hdl_codes/priority_encoder.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

