
function roach_dram_write_tb_config(this_block)

  % Revision History:
  %
  %   05-Mar-2022  (20:11 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/Workspace/simulink_models/DRAM/ROACH2/dram_interface/write/dram_write_intf.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('roach_dram_write_tb');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('en_write');
  this_block.addSimulinkInport('din');
  this_block.addSimulinkInport('din_valid');

  this_block.addSimulinkOutport('dram_rst');
  this_block.addSimulinkOutport('dram_addr');
  this_block.addSimulinkOutport('dram_data');
  this_block.addSimulinkOutport('wr_be');
  this_block.addSimulinkOutport('rwn');
  this_block.addSimulinkOutport('cmd_tag');
  this_block.addSimulinkOutport('cmd_valid');

  dram_rst_port = this_block.port('dram_rst');
  dram_rst_port.setType('UFix_1_0');
  dram_rst_port.useHDLVector(false);
  dram_addr_port = this_block.port('dram_addr');
  dram_addr_port.setType('UFix_25_0');
  dram_data_port = this_block.port('dram_data');
  dram_data_port.setType('UFix_288_0');
  wr_be_port = this_block.port('wr_be');
  wr_be_port.setType('UFix_36_0');
  rwn_port = this_block.port('rwn');
  rwn_port.setType('UFix_1_0');
  rwn_port.useHDLVector(false);
  cmd_tag_port = this_block.port('cmd_tag');
  cmd_tag_port.setType('UFix_32_0');
  cmd_valid_port = this_block.port('cmd_valid');
  cmd_valid_port.setType('UFix_1_0');
  cmd_valid_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('en_write').width ~= 1);
      this_block.setError('Input data type for port "en_write" must have width=1.');
    end

    this_block.port('en_write').useHDLVector(false);

    if (this_block.port('din').width ~= 32);
      this_block.setError('Input data type for port "din" must have width=32.');
    end

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('rtl/roach_dram_write.v');
  this_block.addFile('dram_write_intf.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

