
function atan2_top_config(this_block)

  % Revision History:
  %
  %   04-May-2021  (19:44 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/Workspace/simulink_models/DoA/ROACH2/arte/seba/vec_la_2/atan_top.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('atan2_top');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('eigen1_y');
  this_block.addSimulinkInport('eigen_x');
  this_block.addSimulinkInport('w_valid');

  this_block.addSimulinkOutport('phase1');
  this_block.addSimulinkOutport('phase_valid');

  phase1_port = this_block.port('phase1');
  phase1_port.setType('UFix_16_0');
  phase_valid_port = this_block.port('phase_valid');
  phase_valid_port.setType('UFix_1_0');
  phase_valid_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('eigen1_y').width ~= 16);
      this_block.setError('Input data type for port "eigen1_y" must have width=16.');
    end

    if (this_block.port('eigen_x').width ~= 16);
      this_block.setError('Input data type for port "eigen_x" must have width=16.');
    end

    if (this_block.port('w_valid').width ~= 1);
      this_block.setError('Input data type for port "w_valid" must have width=1.');
    end

    this_block.port('w_valid').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('DIN_WIDTH','integer','16');
  this_block.addGeneric('VECTOR_LEN','integer','512');
  this_block.addGeneric('ATAN_FILE','string','"/home/seba/Workspace/simulink_models/DoA/ROACH2/arte/seba/vec_la_2/init_mem/atan_rom.hex"');

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  path = '/home/seba/Workspace/simulink_models/DoA/ROACH2/arte/seba/vec_la_2/';
  this_block.addFile(strcat(path,'atan_top.v'));

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

