
function agc_top_config(this_block)

  % Revision History:
  %
  %   05-Apr-2021  (18:35 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/seba/Workspace/simulink_models/Tests/ROACH2/agc/hdl_codes/agc_top.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('agc_top');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('rst');
  this_block.addSimulinkInport('din');
  this_block.addSimulinkInport('din_valid');
  this_block.addSimulinkInport('ref_pow');
  this_block.addSimulinkInport('error_coef');

  this_block.addSimulinkOutport('gain_out');
  this_block.addSimulinkOutport('gain_out_valid');
  this_block.addSimulinkOutport('dout');
  this_block.addSimulinkOutport('dout_valid');

  gain_out_port = this_block.port('gain_out');
  gain_out_port.setType('UFix_16_0');
  gain_out_valid_port = this_block.port('gain_out_valid');
  gain_out_valid_port.setType('UFix_1_0');
  gain_out_valid_port.useHDLVector(false);
  dout_port = this_block.port('dout');
  dout_port.setType('UFix_192_0');
  dout_valid_port = this_block.port('dout_valid');
  dout_valid_port.setType('UFix_1_0');
  dout_valid_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('rst').width ~= 1);
      this_block.setError('Input data type for port "rst" must have width=1.');
    end

    this_block.port('rst').useHDLVector(false);

    if (this_block.port('din').width ~= 64);
      this_block.setError('Input data type for port "din" must have width=64.');
    end

    if (this_block.port('din_valid').width ~= 1);
      this_block.setError('Input data type for port "din_valid" must have width=1.');
    end

    this_block.port('din_valid').useHDLVector(false);

    if (this_block.port('ref_pow').width ~= 16);
      this_block.setError('Input data type for port "ref_pow" must have width=16.');
    end

    if (this_block.port('error_coef').width ~= 16);
      this_block.setError('Input data type for port "error_coef" must have width=16.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);

  % (!) Custimize the following generic settings as appropriate. If any settings depend
  %      on input types, make the settings in the "inputTypesKnown" code block.
  %      The addGeneric function takes  3 parameters, generic name, type and constant value.
  %      Supported types are boolean, real, integer and string.
  this_block.addGeneric('DIN_WIDTH','integer','8');
  this_block.addGeneric('DIN_POINT','integer','7');
  this_block.addGeneric('PARALLEL','integer','8');
  this_block.addGeneric('DELAY_LINE','integer','64');
  this_block.addGeneric('UPDATE_CYCLES','integer','1024');
  this_block.addGeneric('COEF_WIDTH','integer','16');
  this_block.addGeneric('COEF_POINT','integer','8');
  this_block.addGeneric('GAIN_WIDTH','integer','16');
  this_block.addGeneric('GAIN_POINT','integer','8');
  this_block.addGeneric('GAIN_HIGH','integer','2048');
  this_block.addGeneric('GAIN_LOW','integer','0');

  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  dir = '/home/seba/Workspace/simulink_models/Misc/ROACH2/AGC/hdl_codes/';

  this_block.addFile(strcat(dir,'bram_infer.v'));
  this_block.addFile(strcat(dir,'adder_tree.v'));
  this_block.addFile(strcat(dir,'parallel_mult.v'));
  this_block.addFile(strcat(dir,'moving_average_unsign.v'));
  this_block.addFile(strcat(dir,'avg_pow.v'));
  this_block.addFile(strcat(dir,'signed_cast.v'));
  this_block.addFile(strcat(dir,'agc.v'));
  this_block.addFile(strcat(dir,'agc_top.v'));

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

